#!/bin/bash
# MrWnn 2016-10-11 15:58:34

who_am_i=`/usr/bin/whoami`

if [ -e /etc/bashrc ]
then 
  path_bashrc=/etc/bashrc
elif [[ ${who_am_i} == root && -e /root/.bashrc ]]
then
  path_bashrc=/root/.bashrc
fi

echo " 
alias cp='cp -i'
alias l.='ls -d .* --color=auto'
alias ll='ls -l --color=auto'
alias ls='ls --color=auto'
alias mv='mv -i'
alias rm='rm -i'
alias vi='vim'
alias which='alias | /usr/bin/which --tty-only --read-alias --show-dot --show-tiled'
" >> ${path_bashrc}

source ${path_bashrc}

